### PR TITLE
Docker compose

### PR DESCRIPTION
**Pull request by whereismyjetpack**
[wip] - variables likely need cleaned up 
moved testing to another docker-compose file so that we can use the same network stack and variables.

### CODE REVIEW

**Comment by whereismyjetpack** [comment]
I'm not sure if minio needs to be in the main docker-compose file, when i run locally i rely on scholarsphere's minio. i left it in case you're developing strictly against that one. i did make the variables parameterizable so that one could hook in scholarsphere if they decide. 

you'd have to run `docker-compose up listener` to only fire up the listener and rely on another minio

**Comment by awead** [comment]
@whereismyjetpack doesn't matter to me, I was cribbing off of S4, but I like this solution better.

**Comment by whereismyjetpack** [comment]
I'll leave it. this allows for both workflows to work. i.e set vars for scholarsphere, and running `docker-compose up listener` and setting vars for local minio and running `docker-compose up `

**Comment by whereismyjetpack** [comment]
armed with that information, i can DRY this up a bit. please hold.

**Comment by awead** [comment]
Combined into #21

**Pull request closed without merging**
