### PR TITLE
store gems in volume for persistence

### PR DESCRIPTION
**Pull request by whereismyjetpack**

### CODE REVIEW

**Comment by awead** [comment]
@whereismyjetpack If I do a `docker-compose down` then `up`, I still need to re-run bundle install to get the gems. Is the idea here that we don't have to do that? Or do the gems get cleared out with each down/up cycle regardless?

**Comment by whereismyjetpack** [comment]
Your bundle will persist through restarts

**Comment by whereismyjetpack** [comment]
Of course I screwed up again... Depends on clamav pr. I tried to split them all up but they leaked into one another

**Comment by awead** [comment]
@whereismyjetpack just for clarity, the bundle persists through restarts, but not up/down cycles? (that's ok by me)

**Comment by whereismyjetpack** [comment]
Once all 3 are merged it will. 

A `docker-compose down -v` will blow away volumes for a "clean" start

**Pull request merged**
